-- MorgesDartsConnect — full Supabase schema setup
-- Generated by concatenating migrations 0001..0005 in order.
-- Paste this whole file into Supabase → SQL Editor → Run.

-- ============================================================
-- RESET — drop everything created by MorgesDartsConnect first.
-- WARNING: this DELETES all existing data in these tables.
-- CASCADE also removes their policies, triggers, indexes and FKs.
-- ============================================================
drop table if exists public.match_players cascade;
drop table if exists public.team_players  cascade;
drop table if exists public.matches       cascade;
drop table if exists public.encounters    cascade;
drop table if exists public.teams         cascade;
drop table if exists public.players       cascade;
drop table if exists public.seasons       cascade;
drop function if exists public.set_updated_at() cascade;

-- ============================================================
-- 0001_init.sql
-- ============================================================
-- ============================================================================
-- Darts platform — initial schema (multi-season, event-sourced matches)
--
-- Design notes
--  * Matches stay EVENT-SOURCED: we persist { config, events } as jsonb and
--    recompute every stat with the same pure TypeScript engine. No stat is
--    ever stored denormalized -> always consistent and correctable.
--  * Multi-season is data-driven: adding 2027/2028, 2028/2029, ... is just a
--    new row in `seasons`. No schema change required.
--  * Security: anonymous = read-only; only authenticated users (the single
--    admin account) can write. Enforced by Row-Level Security (RLS).
-- ============================================================================

create extension if not exists "pgcrypto";

-- updated_at helper -----------------------------------------------------------
create or replace function public.set_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

-- seasons ---------------------------------------------------------------------
create table if not exists public.seasons (
  id          uuid primary key default gen_random_uuid(),
  name        text not null unique,            -- e.g. '2026/2027'
  starts_on   date,
  ends_on     date,
  is_current  boolean not null default false,
  created_at  timestamptz not null default now()
);

-- Only one current season at a time.
create unique index if not exists seasons_one_current
  on public.seasons (is_current) where (is_current);

-- players ---------------------------------------------------------------------
create table if not exists public.players (
  id          uuid primary key default gen_random_uuid(),
  name        text not null,
  color       text,
  active      boolean not null default true,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);
create index if not exists players_active_idx on public.players (active);
create index if not exists players_name_idx on public.players (lower(name));

drop trigger if exists trg_players_updated on public.players;
create trigger trg_players_updated before update on public.players
  for each row execute function public.set_updated_at();

-- matches (event log lives here) ----------------------------------------------
create table if not exists public.matches (
  id                  uuid primary key default gen_random_uuid(),
  season_id           uuid not null references public.seasons(id) on delete restrict,
  config              jsonb not null,                 -- GameConfig snapshot
  events              jsonb not null default '[]',    -- GameEvent[]
  -- denormalized columns for fast filtering (kept in sync from config/state)
  mode                text not null,                  -- 'SINGLE' | 'DOUBLE'
  variant             integer not null,               -- 501 | 601
  status              text not null default 'IN_PROGRESS', -- IN_PROGRESS|GAME_OVER|ABANDONED
  winner_participant  text,
  created_at          timestamptz not null default now(),
  updated_at          timestamptz not null default now(),
  finished_at         timestamptz
);
create index if not exists matches_season_idx on public.matches (season_id);
create index if not exists matches_status_idx on public.matches (status);
create index if not exists matches_created_idx on public.matches (created_at);
create index if not exists matches_mode_idx on public.matches (mode);

drop trigger if exists trg_matches_updated on public.matches;
create trigger trg_matches_updated before update on public.matches
  for each row execute function public.set_updated_at();

-- match_players (link table -> fast per-player season filtering) ---------------
create table if not exists public.match_players (
  match_id        uuid not null references public.matches(id) on delete cascade,
  player_id       uuid not null references public.players(id) on delete restrict,
  participant_id  text not null,                      -- side within the match
  primary key (match_id, player_id)
);
create index if not exists match_players_player_idx on public.match_players (player_id);

-- ============================================================================
-- Seed: first season
-- ============================================================================
insert into public.seasons (name, starts_on, ends_on, is_current)
values ('2026/2027', '2026-09-01', '2027-08-31', true)
on conflict (name) do nothing;

-- ============================================================================
-- Row-Level Security: read = everyone, write = authenticated (admin) only
-- ============================================================================
alter table public.seasons       enable row level security;
alter table public.players       enable row level security;
alter table public.matches       enable row level security;
alter table public.match_players enable row level security;

-- helper to (re)create a read+write policy pair on a table
do $$
declare t text;
begin
  foreach t in array array['seasons','players','matches','match_players'] loop
    execute format('drop policy if exists "%s_read" on public.%I', t, t);
    execute format('drop policy if exists "%s_write" on public.%I', t, t);
    execute format(
      'create policy "%s_read" on public.%I for select using (true)', t, t);
    execute format(
      'create policy "%s_write" on public.%I for all to authenticated using (true) with check (true)', t, t);
  end loop;
end$$;


-- ============================================================
-- 0002_public_scoring.sql
-- ============================================================
-- ============================================================================
-- Open scoring: matches can be created & scored WITHOUT signing in.
--
-- Players and seasons remain admin-only (authenticated). For matches, anyone
-- (anon) may insert and update; only the admin (authenticated) may delete, so
-- match history can't be wiped by anonymous users.
-- ============================================================================

-- matches: replace the admin-only write policy with granular public ones
drop policy if exists "matches_write" on public.matches;

create policy "matches_insert" on public.matches
  for insert with check (true);                 -- anon + authenticated

create policy "matches_update" on public.matches
  for update using (true) with check (true);    -- anon + authenticated

create policy "matches_delete" on public.matches
  for delete to authenticated using (true);     -- admin only

-- match_players: anon may link players to a match; admin may remove
drop policy if exists "match_players_write" on public.match_players;

create policy "match_players_insert" on public.match_players
  for insert with check (true);

create policy "match_players_delete" on public.match_players
  for delete to authenticated using (true);


-- ============================================================
-- 0003_championship.sql
-- ============================================================
-- ============================================================================
-- Championship mode: teams (many-to-many with players) and encounters.
--
-- An "encounter" is a tie between two teams made of a fixed sequence of
-- fixtures (4 singles, 2 doubles, 4 singles). Each played fixture reuses the
-- normal `matches` engine, tagged with encounter_id + fixture_index so it stays
-- out of the regular stats and feeds the championship stats instead.
--
-- Security: teams and encounters (championship scoring) require the admin
-- account (authenticated). Regular matches stay public.
-- ============================================================================

-- teams -----------------------------------------------------------------------
create table if not exists public.teams (
  id         uuid primary key default gen_random_uuid(),
  name       text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists teams_name_idx on public.teams (lower(name));

drop trigger if exists trg_teams_updated on public.teams;
create trigger trg_teams_updated before update on public.teams
  for each row execute function public.set_updated_at();

-- team_players (many-to-many; a player may belong to several teams) -----------
create table if not exists public.team_players (
  team_id   uuid not null references public.teams(id) on delete cascade,
  player_id uuid not null references public.players(id) on delete cascade,
  primary key (team_id, player_id)
);
create index if not exists team_players_player_idx on public.team_players (player_id);

-- encounters ------------------------------------------------------------------
create table if not exists public.encounters (
  id            uuid primary key default gen_random_uuid(),
  season_id     uuid not null references public.seasons(id) on delete restrict,
  team_a_id     uuid not null references public.teams(id) on delete restrict,
  team_b_id     uuid not null references public.teams(id) on delete restrict,
  plan          jsonb not null,            -- fixtures + compositions + settings
  status        text not null default 'IN_PROGRESS', -- IN_PROGRESS|FINISHED|ABANDONED
  current_index integer not null default 0,
  score_a       integer not null default 0,
  score_b       integer not null default 0,
  winner        text,                       -- 'A' | 'B' | null
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now(),
  finished_at   timestamptz
);
create index if not exists encounters_status_idx on public.encounters (status);
create index if not exists encounters_season_idx on public.encounters (season_id);

drop trigger if exists trg_encounters_updated on public.encounters;
create trigger trg_encounters_updated before update on public.encounters
  for each row execute function public.set_updated_at();

-- link matches to encounters (nullable -> regular matches unaffected) ----------
alter table public.matches add column if not exists encounter_id uuid
  references public.encounters(id) on delete cascade;
alter table public.matches add column if not exists fixture_index integer;
create index if not exists matches_encounter_idx on public.matches (encounter_id);

-- ============================================================================
-- Row-Level Security
-- ============================================================================
alter table public.teams        enable row level security;
alter table public.team_players enable row level security;
alter table public.encounters   enable row level security;

-- teams / team_players / encounters: read public, write admin (authenticated)
do $$
declare t text;
begin
  foreach t in array array['teams','team_players','encounters'] loop
    execute format('drop policy if exists "%s_read" on public.%I', t, t);
    execute format('drop policy if exists "%s_write" on public.%I', t, t);
    execute format('create policy "%s_read" on public.%I for select using (true)', t, t);
    execute format('create policy "%s_write" on public.%I for all to authenticated using (true) with check (true)', t, t);
  end loop;
end$$;

-- matches: championship matches (encounter_id set) require authentication;
-- regular matches (encounter_id null) stay publicly writable.
drop policy if exists "matches_insert" on public.matches;
drop policy if exists "matches_update" on public.matches;

create policy "matches_insert" on public.matches
  for insert
  with check (encounter_id is null or (select auth.role()) = 'authenticated');

create policy "matches_update" on public.matches
  for update
  using (encounter_id is null or (select auth.role()) = 'authenticated')
  with check (encounter_id is null or (select auth.role()) = 'authenticated');


-- ============================================================
-- 0004_live_and_lock.sql
-- ============================================================
-- ============================================================================
-- Live spectating + single-scorer lock.
--
-- 1. Realtime: broadcast `matches` row changes so read-only spectators can
--    follow a game live (no polling needed).
-- 2. Scoring lock: the device actively scoring a match holds a short-lived
--    heartbeat lock (locked_by + locked_at). Another device can only WATCH
--    while the lock is fresh; it can take control once the lock goes stale
--    (the scoring device closed / lost connection).
--
-- Idempotent: safe to re-run.
-- ============================================================================

-- 1. Enable realtime on matches (ignore if already in the publication).
do $$
begin
  alter publication supabase_realtime add table public.matches;
exception
  when duplicate_object then null;
end $$;

-- 2. Lock columns. RLS already governs who may UPDATE a match row:
--    regular matches are anon-updatable, championship matches require the
--    admin — so locking inherits exactly the right permissions.
alter table public.matches add column if not exists locked_by text;
alter table public.matches add column if not exists locked_at timestamptz;


-- ============================================================
-- 0005_training_flag.sql
-- ============================================================
-- ============================================================================
-- Clearly distinguish training (New Game) matches from championship matches.
--
-- A match belongs to a championship exactly when it is linked to an encounter.
-- `is_training` makes that explicit and queryable at the DB level: training
-- games must never feed championship / player stats, rankings or averages.
-- Generated, so it can never drift from encounter_id.
-- ============================================================================
alter table public.matches
  add column if not exists is_training boolean
  generated always as (encounter_id is null) stored;

comment on column public.matches.is_training is
  'True for New Game (training) matches; false for championship matches. Stats use championship only.';
