/**
 * Lightweight FR / EN internationalisation. A tiny dictionary + `t(key)` hook.
 * The chosen language is a UI preference (kept in localStorage — not match
 * data), defaulting to the browser language. Covers the player-facing flows
 * (home, live, TV); `t` falls back to the key so untranslated strings are safe.
 */
import {
  createContext,
  useCallback,
  useContext,
  useMemo,
  useState,
  type ReactNode,
} from 'react';
import { cn } from '@/lib/cn';

export type Lang = 'fr' | 'en';
const KEY = 'darts:lang';

const DICT: Record<string, { en: string; fr: string }> = {
  // --- Premier League + scoring station -------------------------------------
  "scoringStation.eyebrow": { en: "Darts scoring", fr: "Scoring de fléchettes" },
  "scoringStation.title": { en: "Board scoring station", fr: "Poste de scoring" },
  "scoringStation.boardTitle": { en: "Board {number}", fr: "Cible {number}" },
  "scoringStation.chooseBoard": { en: "Choose your board", fr: "Choisissez votre cible" },
  "scoringStation.chooseBoardHelp": { en: "The matches assigned by the tournament manager will appear here automatically.", fr: "Les matchs attribués par le gestionnaire du tournoi apparaîtront ici automatiquement." },
  "scoringStation.boardNumber": { en: "Board number", fr: "Numéro de la cible" },
  "scoringStation.boardPlaceholder": { en: "e.g. 4", fr: "ex. 4" },
  "scoringStation.openBoard": { en: "Open this board", fr: "Ouvrir cette cible" },
  "scoringStation.changeBoard": { en: "Change board", fr: "Changer de cible" },
  "scoringStation.stationReady": { en: "This station is set to board {number}", fr: "Ce poste est associé à la cible {number}" },
  "scoringStation.autoRefresh": { en: "Assignments and scores update automatically.", fr: "Les affectations et les scores se mettent à jour automatiquement." },
  "scoringStation.waitingTournament": { en: "Waiting for tournament data", fr: "En attente des données du tournoi" },
  "scoringStation.waitingTournamentHelp": { en: "Keep this page open. The competition will appear as soon as the tournament website publishes it.", fr: "Gardez cette page ouverte. La compétition apparaîtra dès que le site du tournoi la publiera." },
  "scoringStation.noAssignedMatches": { en: "No match assigned to this board", fr: "Aucun match attribué à cette cible" },
  "scoringStation.noAssignedMatchesHelp": { en: "The list refreshes automatically when the organizer assigns a match.", fr: "La liste se rafraîchit automatiquement lorsqu’un organisateur attribue un match." },
  "scoringStation.matchesToPlay": { en: "Matches to play", fr: "Matchs à jouer" },
  "scoringStation.noPendingMatches": { en: "There are no more matches to play on this board.", fr: "Il n’y a plus de match à jouer sur cette cible." },
  "scoringStation.finishedMatches": { en: "Completed on this board", fr: "Terminés sur cette cible" },
  "scoringStation.next": { en: "Next", fr: "Prochain" },
  "scoringStation.login": { en: "Sign in to score", fr: "Se connecter pour scorer" },
  "scoringStation.connectedLogout": { en: "Connected · sign out", fr: "Connecté · se déconnecter" },
  "scoringStation.localMode": { en: "Local scoring mode", fr: "Mode de scoring local" },
  "premierLeague.title": { en: "Premier League", fr: "Premier League" },
  "premierLeague.noCompetition": { en: "No Premier League competition has been created yet.", fr: "Aucune compétition Premier League n’a encore été créée." },
  "premierLeague.createCompetition": { en: "Create competition", fr: "Créer la compétition" },
  "premierLeague.fixedFormat": { en: "501 · Double Out · fixed formats", fr: "501 · Double Out · formats fixes" },
  "premierLeague.organizer": { en: "Organizer access", fr: "Accès organisateur" },
  "premierLeague.navigation": { en: "Competition navigation", fr: "Navigation de la compétition" },
  "premierLeague.night": { en: "Night {number}", fr: "Night {number}" },
  "premierLeague.finalsNight": { en: "Finals Night", fr: "Finals Night" },
  "premierLeague.standings": { en: "Standings", fr: "Classement" },
  "premierLeague.generalStandings": { en: "League standings", fr: "Classement général" },
  "premierLeague.fullStandings": { en: "Full standings", fr: "Classement complet" },
  "premierLeague.finalsUnavailable": { en: "Finals Night becomes available after all seven league Nights are complete.", fr: "La Finals Night devient disponible lorsque les sept Nights de ligue sont terminées." },
  "premierLeague.champion": { en: "{player} is the champion!", fr: "{player} est champion !" },
  "premierLeague.finalist": { en: "Finalist", fr: "Finaliste" },
  "premierLeague.semiFinalists": { en: "Semi-finalists", fr: "Demi-finalistes" },
  "premierLeague.chooseStarter": { en: "Who throws first in leg 1?", fr: "Qui lance en premier au leg 1 ?" },
  "premierLeague.starterAlternates": { en: "The opening throw alternates automatically each leg.", fr: "Le premier lancer alterne automatiquement à chaque leg." },
  "premierLeague.toBeDetermined": { en: "To be determined", fr: "À déterminer" },
  "premierLeague.matchNumber": { en: "Match {number}", fr: "Match {number}" },
  "premierLeague.bestOf": { en: "Best of {number}", fr: "Best of {number}" },
  "premierLeague.start": { en: "Start →", fr: "Démarrer →" },
  "premierLeague.resume": { en: "Resume →", fr: "Reprendre →" },
  "premierLeague.finished": { en: "Finished", fr: "Terminé" },
  "premierLeague.blocked": { en: "Locked", fr: "Bloqué" },
  "premierLeague.matchFinishedSaving": { en: "Match finished — saving before returning to the board…", fr: "Match terminé — enregistrement avant le retour à la cible…" },
  "premierLeague.resultSaveFailed": { en: "The result could not be saved.", fr: "Le résultat n’a pas pu être enregistré." },
  "premierLeague.retry": { en: "Retry", fr: "Réessayer" },
  "premierLeague.errorWinner": { en: "The match winner could not be identified.", fr: "Le vainqueur du match n’a pas pu être identifié." },
  "premierLeague.errorSaveResult": { en: "Failed to save the result.", fr: "Impossible d’enregistrer le résultat." },
  "premierLeague.errorStart": { en: "Failed to start the match.", fr: "Impossible de démarrer le match." },
  "premierLeague.round.QUARTER_FINAL": { en: "Quarter-finals", fr: "Quarts de finale" },
  "premierLeague.round.SEMI_FINAL": { en: "Semi-finals", fr: "Demi-finales" },
  "premierLeague.round.FINAL": { en: "Final", fr: "Finale" },
  "premierLeague.fixtureStatus.BLOCKED": { en: "Waiting for qualifiers", fr: "En attente des qualifiés" },
  "premierLeague.fixtureStatus.AVAILABLE": { en: "Available", fr: "Disponible" },
  "premierLeague.fixtureStatus.IN_PROGRESS": { en: "In progress", fr: "En cours" },
  "premierLeague.fixtureStatus.FINISHED": { en: "Finished", fr: "Terminé" },
  "premierLeague.nightStatus.SCHEDULED": { en: "Scheduled", fr: "Planifiée" },
  "premierLeague.nightStatus.IN_PROGRESS": { en: "In progress", fr: "En cours" },
  "premierLeague.nightStatus.FINISHED": { en: "Finished", fr: "Terminée" },
  "premierLeague.competitionStatus.IN_PROGRESS": { en: "League phase in progress", fr: "Phase de ligue en cours" },
  "premierLeague.competitionStatus.FINALS_READY": { en: "Finals Night ready", fr: "Finals Night disponible" },
  "premierLeague.competitionStatus.FINALS_IN_PROGRESS": { en: "Finals Night in progress", fr: "Finals Night en cours" },
  "premierLeague.competitionStatus.FINISHED": { en: "Competition complete", fr: "Compétition terminée" },
  "premierLeague.table.position": { en: "#", fr: "#" },
  "premierLeague.table.player": { en: "Player", fr: "Joueur" },
  "premierLeague.table.points": { en: "Pts", fr: "Pts" },
  "premierLeague.table.nights": { en: "Nights", fr: "Nights" },
  "premierLeague.table.nightWins": { en: "Night wins", fr: "Victoires de Night" },
  "premierLeague.table.finalsLost": { en: "Finals lost", fr: "Finales perdues" },
  "premierLeague.table.semis": { en: "Semi-final exits", fr: "Demi-finales" },
  "premierLeague.table.matchesPlayed": { en: "MP", fr: "MJ" },
  "premierLeague.table.matchesWon": { en: "MW", fr: "MG" },
  "premierLeague.table.matchesLost": { en: "ML", fr: "MP" },
  "premierLeague.table.legsWon": { en: "LW", fr: "LG" },
  "premierLeague.table.legsLost": { en: "LL", fr: "LP" },
  "premierLeague.table.legDifference": { en: "LD", fr: "Diff." },
  "premierLeague.admin.title": { en: "Premier League organizer", fr: "Organisation Premier League" },
  "premierLeague.admin.competitionName": { en: "Competition name", fr: "Nom de la compétition" },
  "premierLeague.admin.chooseSeason": { en: "Choose a season", fr: "Choisir une saison" },
  "premierLeague.admin.noSeason": { en: "No season is available. Create one in Supabase before continuing.", fr: "Aucune saison n’est disponible. Créez-en une dans Supabase avant de continuer." },
  "premierLeague.admin.selectEight": { en: "Select exactly eight players", fr: "Sélectionnez exactement huit joueurs" },
  "premierLeague.admin.optionalDates": { en: "Optional dates", fr: "Dates facultatives" },
  "premierLeague.admin.creating": { en: "Creating…", fr: "Création…" },
  "premierLeague.admin.correctLast": { en: "Correct last result", fr: "Corriger le dernier résultat" },
  "premierLeague.admin.correctTitle": { en: "Reopen the last result?", fr: "Rouvrir le dernier résultat ?" },
  "premierLeague.admin.correctMessage": { en: "The winning visit will be removed and every dependent bracket and standing will be recalculated. This is blocked if the next dependent match has started.", fr: "La volée gagnante sera retirée et le tableau ainsi que le classement seront recalculés. L’action est bloquée si le match dépendant suivant a commencé." },
  "premierLeague.admin.correctAction": { en: "Reopen result", fr: "Rouvrir le résultat" },
  "premierLeague.admin.brackets": { en: "League Night brackets", fr: "Tableaux des Nights de ligue" },
  "premierLeague.admin.bracketHelp": { en: "Quarter-finals may be rearranged before play. Once a Night starts, an explicit organizer confirmation is required and matches already under way remain protected.", fr: "Les quarts peuvent être réorganisés avant le début. Une fois la Night commencée, une confirmation organisateur explicite est requise et les matchs déjà lancés restent protégés." },
  "premierLeague.admin.saveBracket": { en: "Save bracket", fr: "Enregistrer le tableau" },
  "premierLeague.admin.lockedTitle": { en: "Bracket already locked", fr: "Tableau déjà verrouillé" },
  "premierLeague.admin.lockedMessage": { en: "At least one match has started. Only matches not yet under way can still be changed. Confirm this organizer override?", fr: "Au moins un match a commencé. Seuls les matchs non démarrés peuvent encore être modifiés. Confirmer cette dérogation organisateur ?" },
  "premierLeague.admin.forceEdit": { en: "Confirm organizer edit", fr: "Confirmer la modification" },
  "premierLeague.admin.allowFuture": { en: "Allow early start", fr: "Autoriser le démarrage anticipé" },
  "premierLeague.admin.removeOverride": { en: "Remove early-start override", fr: "Retirer la dérogation" },
  "premierLeague.admin.unlockTitle": { en: "Allow this future Night?", fr: "Autoriser cette Night future ?" },
  "premierLeague.admin.unlockMessage": { en: "This explicit organizer override allows matches to start before the previous Night is complete.", fr: "Cette dérogation explicite permet de démarrer les matchs avant la fin de la Night précédente." },
  "premierLeague.admin.unlockAction": { en: "Allow early start", fr: "Autoriser" },
  "premierLeague.error.COMPETITION_NAME_REQUIRED": { en: "Enter a competition name.", fr: "Saisissez un nom de compétition." },
  "premierLeague.error.PREMIER_LEAGUE_REQUIRES_EIGHT_UNIQUE_PLAYERS": { en: "Select exactly eight distinct players.", fr: "Sélectionnez exactement huit joueurs distincts." },
  "premierLeague.error.SEASON_REQUIRED": { en: "Select an available season.", fr: "Sélectionnez une saison disponible." },
  "premierLeague.error.PLAYER_NOT_FOUND": { en: "One selected player no longer exists.", fr: "Un joueur sélectionné n’existe plus." },
  "premierLeague.error.PLAYER_NOT_IN_COMPETITION": { en: "Every bracket player must belong to the competition.", fr: "Chaque joueur du tableau doit appartenir à la compétition." },
  "premierLeague.error.FOUR_QUARTER_FINALS_REQUIRED": { en: "Four quarter-finals are required.", fr: "Quatre quarts de finale sont requis." },
  "premierLeague.error.BRACKET_LOCKED": { en: "This bracket is locked because play has started.", fr: "Ce tableau est verrouillé car le jeu a commencé." },
  "premierLeague.error.STARTED_FIXTURE_CANNOT_BE_CHANGED": { en: "A match that has started or finished cannot be reassigned.", fr: "Un match commencé ou terminé ne peut pas être réattribué." },
  "premierLeague.error.INVALID_QUARTER_FINAL_LINEUP": { en: "Each of the eight players must appear exactly once.", fr: "Chacun des huit joueurs doit apparaître exactement une fois." },
  "premierLeague.error.DEPENDENT_FIXTURE_ALREADY_STARTED": { en: "The dependent next match has already started, so this result cannot be reopened safely.", fr: "Le match dépendant suivant a déjà commencé : ce résultat ne peut pas être rouvert sans incohérence." },
  "premierLeague.error.NO_FINISHED_RESULT": { en: "There is no finished result to correct.", fr: "Aucun résultat terminé ne peut être corrigé." },
  "premierLeague.error.FIXTURE_NOT_AVAILABLE": { en: "This match is not available yet.", fr: "Ce match n’est pas encore disponible." },
  "premierLeague.error.COMPETITION_NOT_FOUND": { en: "The competition could not be found.", fr: "La compétition est introuvable." },
  "premierLeague.error.UNKNOWN": { en: "The action could not be completed.", fr: "L’action n’a pas pu être effectuée." },
  'home.tagline': {
    en: 'Match scoring — 501 / 601 Double Out',
    fr: 'Scoring de match — 501 / 601 Double Out',
  },
  'home.new': { en: 'New practice match', fr: "Nouveau match d'entraînement" },
  'home.championship': { en: '🏆 Championship', fr: '🏆 Championnat' },
  'home.live': { en: '📺 Watch live', fr: '📺 En direct' },
  'home.tv': { en: '📺 Club TV mode', fr: '📺 Mode TV du club' },
  'home.admin': { en: 'Statistics', fr: 'Statistiques' },
  'home.resume': { en: 'Resume →', fr: 'Reprendre →' },
  'home.gameInProgress': { en: 'Match in progress', fr: 'Match en cours' },
  'home.gamesInProgress': { en: 'matches in progress', fr: 'matchs en cours' },
  'home.champInProgress': {
    en: '🏆 Championship in progress',
    fr: '🏆 Championnat en cours',
  },
  'home.match': { en: 'match', fr: 'match' },
  'home.syncing': { en: 'Syncing…', fr: 'Synchronisation…' },
  'home.celebrationRulesButton': { en: 'Very official rules', fr: 'Règlement anti-rabat-joie' },
  'home.celebrationRulesTitle': { en: 'The anti-killjoy rulebook', fr: 'Le règlement anti-rabat-joie' },
  'home.celebrationRule.1': {
    en: 'If you hit a nice checkout, celebrate. If someone sighs, do it again, slower.',
    fr: 'Si tu fais un beau checkout, tu célèbres. Si quelqu’un soupire, tu recommences plus lentement.',
  },
  'home.celebrationRule.2': {
    en: 'A quietly announced 180 only counts halfway. The whole room needs to know.',
    fr: 'Un 180 annoncé calmement ne compte qu’à moitié. Il faut que la salle soit au courant.',
  },
  'home.celebrationRule.3': {
    en: 'Any “come on, enough” automatically adds five seconds of celebration.',
    fr: 'Toute phrase du style “ça va, c’est bon” ajoute automatiquement 5 secondes de célébration.',
  },
  'home.celebrationRule.4': {
    en: 'If someone says “we’re not on TV”, immediately play like it is the world final.',
    fr: 'Si quelqu’un dit “on n’est pas à la télé”, il faut immédiatement jouer comme si on était en finale mondiale.',
  },
  'home.celebrationRule.5': {
    en: 'A double 1 that goes in deserves the same respect as a 170. Sometimes more, because there was pain.',
    fr: 'Un double 1 qui rentre mérite autant de respect qu’un 170. Parfois plus, parce qu’il y avait de la souffrance.',
  },
  'home.celebrationRule.6': {
    en: 'The player pretending not to watch the celebration is officially the main audience.',
    fr: 'Le joueur qui fait semblant de ne pas regarder la célébration est officiellement le public principal.',
  },
  'home.celebrationRule.7': {
    en: 'An ugly checkout is celebrated too. Beauty is a social construct.',
    fr: 'Un check dégueulasse, ça se fête aussi. La beauté est une construction sociale.',
  },
  'home.celebrationRule.8': {
    en: 'If your opponent rolls their eyes, they saw it. Mission accomplished.',
    fr: 'Si ton adversaire lève les yeux au ciel, c’est qu’il a vu. Mission accomplie.',
  },
  'home.celebrationRule.9': {
    en: 'A forced “well played” is accepted, but it must come with a devastated look.',
    fr: 'Le “bien joué” forcé est accepté, mais il doit être accompagné d’un regard détruit.',
  },
  'home.celebrationRule.10': {
    en: 'Any criticized celebration may be replayed in the extended version next leg.',
    fr: 'Toute célébration critiquée pourra être rejouée en version longue au prochain leg.',
  },
  'common.home': { en: '← Home', fr: '← Accueil' },
  'common.back': { en: '← Back', fr: '← Retour' },
  'common.backToApp': { en: '← Back to app', fr: "← Retour à l'application" },
  'common.app': { en: '← App', fr: '← Application' },
  'common.cancel': { en: 'Cancel', fr: 'Annuler' },
  'common.confirm': { en: 'Confirm', fr: 'Confirmer' },
  'common.save': { en: 'Save', fr: 'Enregistrer' },
  'common.saving': { en: 'Saving…', fr: 'Enregistrement…' },
  'common.loadingShort': { en: 'Loading…', fr: 'Chargement…' },
  'common.loading': { en: 'Loading…', fr: 'Chargement…' },
  'common.dash': { en: '—', fr: '—' },
  'common.vs': { en: 'vs', fr: 'contre' },
  'common.final': { en: 'Final', fr: 'Final' },
  'common.live': { en: 'Live', fr: 'Direct' },
  'common.player': { en: 'player', fr: 'joueur' },
  'common.players': { en: 'players', fr: 'joueurs' },
  'common.match': { en: 'match', fr: 'match' },
  'common.matches': { en: 'matches', fr: 'matchs' },
  'common.close': { en: 'Close', fr: 'Fermer' },
  'common.delete': { en: 'Delete', fr: 'Supprimer' },
  'common.search': { en: 'Search…', fr: 'Rechercher…' },
  'common.current': { en: 'current', fr: 'en cours' },
  'common.winner': { en: 'winner', fr: 'vainqueur' },
  'common.won': { en: 'won', fr: 'a gagné' },
  'common.inProgress': { en: 'in progress', fr: 'en cours' },
  'common.forfeit': { en: 'forfeit', fr: 'forfait' },
  'common.encounter': { en: 'team match', fr: 'rencontre' },
  'common.encounters': { en: 'team matches', fr: 'rencontres' },
  'common.thisSeason': { en: 'this season', fr: 'cette saison' },
  'common.email': { en: 'Email', fr: 'E-mail' },
  'common.password': { en: 'Password', fr: 'Mot de passe' },
  'game.doubleOut': { en: 'Double Out', fr: 'Double Out' },
  'game.singles': { en: 'Singles', fr: 'Simples' },
  'game.doubles': { en: 'Doubles', fr: 'Doubles' },
  'game.legs': { en: 'legs', fr: 'legs' },
  'game.leg': { en: 'leg', fr: 'leg' },
  'game.firstTo': { en: 'first to', fr: 'premier à' },
  'game.throwing': { en: 'throwing', fr: 'lance' },
  'game.winner': { en: 'winner', fr: 'vainqueur' },
  'game.avg': { en: 'avg', fr: 'moy.' },
  'game.toThrow': { en: '{player} to throw', fr: 'À {player} de lancer' },
  'game.toThrowSuffix': { en: 'to throw', fr: 'doit lancer' },
  'game.checkout': { en: 'checkout {score}', fr: 'checkout {score}' },
  'game.visitsLeg': { en: 'visits · leg {leg}', fr: 'volées · leg {leg}' },
  'game.scoreLeft': { en: 'score · left', fr: 'score · reste' },
  'game.bust': { en: 'BUST', fr: 'BUST' },
  'game.typeScore': { en: 'Type a score', fr: 'Saisir un score' },
  'game.finishHint': { en: 'Checkout — hold 1 / 2 / 3 for the darts used', fr: 'Checkout — maintenir 1 / 2 / 3 pour le nombre de fléchettes' },
  'game.miss': { en: 'Miss', fr: 'Miss' },
  'game.validate': { en: 'Validate', fr: 'Valider' },
  'game.remaining': { en: 'Remaining', fr: 'Reste' },
  'game.remainingTap': { en: 'Remaining (tap to validate)', fr: 'Reste (toucher pour valider)' },
  'game.darts': { en: 'darts', fr: 'fléchettes' },
  'game.hold': { en: 'hold', fr: 'maintenir' },
  'game.legComplete': { en: 'Leg {leg} complete!', fr: 'Leg {leg} terminé !' },
  'game.checkedOut': { en: '{player} checked out {score}', fr: 'Checkout de {score} pour {player}' },
  'game.finalDartsQuestion': { en: 'How many darts were used for the checkout?', fr: 'Combien de fléchettes pour le checkout ?' },
  'game.cannotCheckoutInDarts': { en: '{score} cannot be checked out in {darts} {unit}', fr: 'Checkout de {score} impossible en {darts} {unit}' },
  'game.dartSingular': { en: 'dart', fr: 'fléchette' },
  'game.needsDarts': { en: '{score} needs at least {darts} darts to check out', fr: 'Le checkout de {score} demande au moins {darts} fléchettes' },
  'game.loadingMatch': { en: 'Loading match…', fr: 'Chargement du match…' },
  'game.resumeProtected': { en: '🔒 Resuming a match in progress is protected. Sign in with the organizer account to take control.', fr: '🔒 La reprise d’un match en cours est protégée. Connectez-vous avec le compte organisateur pour prendre le contrôle.' },
  'game.lockedTitle': { en: 'Match in progress elsewhere', fr: 'Match en cours ailleurs' },
  'game.lockedText': { en: 'This match is being scored on another device. You can follow it live, or take over once that device stops.', fr: 'Ce match est scoré sur un autre appareil. Vous pouvez le suivre en direct ou reprendre la main quand cet appareil s’arrête.' },
  'game.undo': { en: '↩ Undo', fr: '↩ Annuler' },
  'game.forfeitLeg': { en: 'Forfeit leg', fr: 'Abandonner le leg' },
  'game.forfeitMatch': { en: 'Forfeit match', fr: 'Abandonner le match' },
  'game.forfeitLegTitle': { en: 'Forfeit this leg?', fr: 'Abandonner ce leg ?' },
  'game.forfeitLegMessage': { en: 'The leg will be awarded to the opponent. {player} forfeits.', fr: 'Le leg sera attribué à l’adversaire. {player} abandonne.' },
  'game.forfeitMatchTitle': { en: 'Forfeit the match?', fr: 'Abandonner le match ?' },
  'game.forfeitMatchMessage': { en: 'The match ends immediately. The opponent wins and partial stats are generated.', fr: 'Le match se termine immédiatement. L’adversaire gagne et les statistiques partielles sont générées.' },
  'game.offlineTitle': { en: 'Offline — the match is kept in memory and will save automatically once the connection is back', fr: 'Hors ligne — le match reste en mémoire et sera enregistré automatiquement au retour de la connexion' },
  'game.savingTitle': { en: 'Saving to the database…', fr: 'Enregistrement en base…' },
  'game.offlineRetrying': { en: 'Offline — retrying', fr: 'Hors ligne — nouvelle tentative' },
  'game.starts': { en: '{starter} throws first', fr: '{starter} lance en premier' },
  'game.startsLegTitle': { en: 'Throws first this leg', fr: 'Lance en premier dans ce leg' },
  'game.shortInfo': { en: '{variant} DO · first to {legs}', fr: '{variant} DO · premier à {legs}' },
  'validation.scoreRange': { en: 'Score must be between 0 and 180.', fr: 'Le score doit être compris entre 0 et 180.' },
  'validation.impossible': { en: 'Impossible score with three darts.', fr: 'Score impossible avec trois fléchettes.' },
  'validation.overRemaining': { en: 'Score is higher than what’s left ({remaining}).', fr: 'Le score est supérieur au reste ({remaining}).' },
  'validation.leavesOne': { en: 'Cannot leave 1 — a double is required to finish.', fr: 'Impossible de laisser 1 — un double est nécessaire pour finir.' },
  'validation.invalidCheckout': { en: '{remaining} cannot be checked out.', fr: 'Checkout impossible sur {remaining}.' },
  'validation.leaveMore': { en: 'You can’t leave more than {remaining}.', fr: 'Impossible de laisser plus que {remaining}.' },
  'validation.exceeds180': { en: 'That visit would exceed 180.', fr: 'Cette volée dépasserait 180.' },
  'live.title': { en: '📺 Live matches', fr: '📺 Matchs en direct' },
  'live.none': {
    en: 'No match is being played right now.',
    fr: 'Aucun match en cours pour le moment.',
  },
  'live.back': { en: '← Live matches', fr: '← Matchs en direct' },
  'live.gone': {
    en: 'This match is no longer available.',
    fr: 'Ce match n’est plus disponible.',
  },
  'live.championship': { en: 'championship', fr: 'championnat' },
  'live.finished': {
    en: '🏆 Championship match finished — see the full recap below.',
    fr: '🏆 Match de championnat terminé — voir le récapitulatif ci-dessous.',
  },
  'live.waiting': {
    en: 'Match finished — waiting for the next match…',
    fr: 'Match terminé — en attente du match suivant…',
  },
  'live.scan': { en: 'Scan to watch live', fr: 'Scanne pour suivre en direct' },
  'live.scanShort': { en: 'Scan to watch', fr: 'Scanne pour regarder' },
  'live.matchLabel': { en: 'match {n} of {total}', fr: 'match {n} sur {total}' },
  'tv.title': { en: 'Club TV', fr: 'TV du club' },
  'tv.exit': { en: 'Exit', fr: 'Quitter' },
  'tv.live': { en: 'live', fr: 'en direct' },
  'tv.idle': {
    en: 'No live match right now',
    fr: 'Aucun match en direct pour le moment',
  },
  'tv.idleHint': {
    en: 'This screen updates automatically when a match starts.',
    fr: 'Cet écran se met à jour automatiquement quand un match démarre.',
  },
  'setup.title': { en: 'New practice match', fr: "Nouveau match d'entraînement" },
  'setup.gameType': { en: 'Match format', fr: 'Format du match' },
  'setup.mode': { en: 'Mode', fr: 'Mode' },
  'setup.legsToWin': { en: 'Legs to win (first to)', fr: 'Legs à gagner' },
  'setup.players': { en: 'Players', fr: 'Joueurs' },
  'setup.team': { en: 'Team {side}', fr: 'Équipe {side}' },
  'setup.playerSlot': { en: 'Player {number}', fr: 'Joueur {number}' },
  'setup.addPlayer': { en: '+ Add player', fr: '+ Ajouter un joueur' },
  'setup.removePlayer': { en: 'Remove player', fr: 'Retirer le joueur' },
  'setup.starts': { en: 'Who starts leg 1?', fr: 'Qui commence le leg 1 ?' },
  'setup.bullUp': { en: '🎯 Bull-off', fr: '🎯 Tirage au bull' },
  'setup.pickManually': { en: 'Pick manually', fr: 'Choisir manuellement' },
  'setup.starterHint': { en: 'The opening throw alternates automatically every leg.', fr: 'Le premier lancer alterne automatiquement à chaque leg.' },
  'setup.continueBull': { en: 'Continue — bull-off', fr: 'Continuer — tirage au bull' },
  'setup.startGame': { en: 'Start match', fr: 'Démarrer le match' },
  'setup.bullText': { en: 'Each {unit} throws for the bull. Who is closest and throws first?', fr: 'Chaque {unit} tire au bull. Qui est le plus proche et lance en premier ?' },
  'setup.unitTeam': { en: 'team', fr: 'équipe' },
  'setup.unitPlayer': { en: 'player', fr: 'joueur' },
  'setup.searchPlayers': { en: 'Search players…', fr: 'Rechercher des joueurs…' },
  'setup.noPlayerFound': { en: 'No player found.', fr: 'Aucun joueur trouvé.' },
  'setup.needPlayers': { en: 'You need at least {count} players (add some under Players).', fr: 'Il faut au moins {count} joueurs (ajoutez-en dans Joueurs).' },
  'setup.addEachTeam': { en: 'Add {count} players to each team.', fr: 'Ajoutez {count} joueurs dans chaque équipe.' },
  'setup.addEachSide': { en: 'Add a player to each side.', fr: 'Ajoutez un joueur de chaque côté.' },
  'stats.winner': { en: '{winner} wins the match!', fr: '{winner} gagne le match !' },
  'stats.statistic': { en: 'Statistic', fr: 'Statistique' },
  'stats.correctScore': { en: '↩ Back — correct the score', fr: '↩ Retour — corriger le score' },
  'stats.row.legs': { en: 'Legs won', fr: 'Legs gagnés' },
  'stats.row.avg': { en: '3-dart average', fr: 'Moyenne 3 fléchettes' },
  'stats.row.first9': { en: 'First 9 avg', fr: 'Moyenne first 9' },
  'stats.row.darts': { en: 'Total darts', fr: 'Total fléchettes' },
  'stats.row.best': { en: 'Best leg (darts)', fr: 'Meilleur leg (fléchettes)' },
  'stats.row.worst': { en: 'Worst leg (darts)', fr: 'Moins bon leg (fléchettes)' },
  'stats.row.high': { en: 'Highest visit', fr: 'Meilleure volée' },
  'stats.row.180': { en: '180s', fr: '180' },
  'stats.row.140': { en: '140+', fr: '140+' },
  'stats.row.100': { en: '100+', fr: '100+' },
  'stats.row.60': { en: '60+', fr: '60+' },
  'stats.row.bust': { en: 'Busts', fr: 'Busts' },
  'stats.row.played': { en: 'P', fr: 'J' },
  'stats.row.wonShort': { en: 'W', fr: 'G' },
  'stats.row.winPct': { en: 'Win%', fr: 'Vict.%' },
  'stats.row.first3': { en: 'First 3', fr: 'First 3' },
  'stats.row.avgCheckout': { en: 'Avg CO', fr: 'CO moy.' },
  'stats.row.bestCheckout': { en: 'Best CO', fr: 'Meilleur CO' },
  'stats.row.highShort': { en: 'High', fr: 'Max' },
  'stats.row.bestLeg': { en: 'Best leg', fr: 'Meilleur leg' },
  'stats.row.player': { en: 'Player', fr: 'Joueur' },
  'stats.row.stat': { en: 'Stat', fr: 'Stat' },
  'admin.title': { en: 'Statistics', fr: 'Statistiques' },
  'admin.players': { en: 'Players', fr: 'Joueurs' },
  'admin.teams': { en: 'Teams', fr: 'Équipes' },
  'admin.championship': { en: 'Championship', fr: 'Championnat' },
  'admin.seasonReview': { en: 'Season review', fr: 'Bilan de saison' },
  'admin.signOut': { en: 'Sign out', fr: 'Déconnexion' },
  'admin.season': { en: 'Season', fr: 'Saison' },
  'admin.signInTitle': { en: 'Sign in', fr: 'Connexion' },
  'admin.captainAccount': { en: 'Captain account', fr: 'Compte capitaine' },
  'admin.captainAssign': { en: 'Assign', fr: 'Associer' },
  'admin.captainRemove': { en: 'Remove account', fr: 'Retirer le compte' },
  'admin.captainEmailPlaceholder': { en: 'captain login email', fr: 'e-mail du compte capitaine' },
  'admin.captainHint': {
    en: 'Create the account in Supabase (Authentication → Users), then bind it here by email. That login manages only this team.',
    fr: 'Créez le compte dans Supabase (Authentication → Users), puis associez-le ici par e-mail. Ce compte ne gère que cette équipe.',
  },
  'admin.signIn': { en: 'Sign in', fr: 'Se connecter' },
  'admin.signingIn': { en: 'Signing in…', fr: 'Connexion…' },
  'admin.signInFailed': { en: 'Sign-in failed', fr: 'Échec de connexion' },
  'admin.restricted': { en: 'Restricted area — authorized staff only.', fr: 'Zone réservée — personnel autorisé uniquement.' },
  'admin.cloudUnavailable': { en: 'Cloud backend not configured — statistics are unavailable.', fr: 'Backend cloud non configuré — les statistiques sont indisponibles.' },
  'admin.actionFailed': { en: 'Action failed', fr: 'Action impossible' },
  'admin.failedLoadTeams': { en: 'Failed to load teams', fr: 'Impossible de charger les équipes' },
  'admin.newPlayerName': { en: 'New player name', fr: 'Nom du nouveau joueur' },
  'admin.addPlayer': { en: 'Add player', fr: 'Ajouter un joueur' },
  'admin.name': { en: 'Name', fr: 'Nom' },
  'admin.added': { en: 'Added', fr: 'Ajouté' },
  'admin.noPlayers': { en: 'No players yet.', fr: 'Aucun joueur pour le moment.' },
  'admin.noMatch': { en: 'No match.', fr: 'Aucun résultat.' },
  'admin.inactive': { en: 'inactive', fr: 'inactif' },
  'admin.deactivate': { en: 'Deactivate', fr: 'Désactiver' },
  'admin.activate': { en: 'Activate', fr: 'Activer' },
  'admin.deletePlayerTitle': { en: 'Delete {name}?', fr: 'Supprimer {name} ?' },
  'admin.deletePlayerMessage': { en: 'If this player has recorded matches, deletion is blocked — deactivate instead.', fr: 'Si ce joueur a des matchs enregistrés, la suppression est bloquée — désactivez-le plutôt.' },
  'admin.newTeamName': { en: 'New team name', fr: 'Nom de la nouvelle équipe' },
  'admin.addTeam': { en: 'Add team', fr: 'Ajouter une équipe' },
  'admin.searchTeams': { en: 'Search teams…', fr: 'Rechercher des équipes…' },
  'admin.noTeams': { en: 'No teams yet.', fr: 'Aucune équipe pour le moment.' },
  'admin.playersButton': { en: 'Players', fr: 'Joueurs' },
  'admin.playerCount': { en: '{count} player', fr: '{count} joueur' },
  'admin.playerCountPlural': { en: '{count} players', fr: '{count} joueurs' },
  'admin.deleteTeamTitle': { en: 'Delete {name}?', fr: 'Supprimer {name} ?' },
  'admin.noMembers': { en: 'No members yet.', fr: 'Aucun membre pour le moment.' },
  'admin.addAPlayer': { en: '+ Add a player…', fr: '+ Ajouter un joueur…' },
  'admin.oneTeamOnly': { en: 'A player can be on one team only.', fr: 'Un joueur ne peut appartenir qu’à une seule équipe.' },
  'admin.allPlayers': { en: 'All players', fr: 'Tous les joueurs' },
  'admin.singlesAndDoubles': { en: 'Singles & Doubles', fr: 'Simples et doubles' },
  'admin.allTime': { en: 'All time', fr: 'Tout' },
  'admin.today': { en: 'Today', fr: 'Aujourd’hui' },
  'admin.last7': { en: 'Last 7 days', fr: '7 derniers jours' },
  'admin.thisMonth': { en: 'This month', fr: 'Ce mois' },
  'admin.thisYear': { en: 'This year', fr: 'Cette année' },
  'admin.custom': { en: 'Custom…', fr: 'Personnalisé…' },
  'admin.counts': { en: '{matches} matches · {players} players', fr: '{matches} matchs · {players} joueurs' },
  'admin.exportCsv': { en: 'CSV', fr: 'CSV' },
  'admin.reviewCounts': { en: '{matches} matches · {encounters} team matches · {players} players', fr: '{matches} matchs · {encounters} rencontres · {players} joueurs' },
  'admin.noStats': { en: 'No stats for these filters yet.', fr: 'Aucune statistique pour ces filtres.' },
  'admin.matchHistory': { en: 'match history', fr: 'historique des matchs' },
  'admin.scoring': { en: 'Scoring', fr: 'Scoring' },
  'admin.noMatchesFilters': { en: 'No matches for these filters.', fr: 'Aucun match pour ces filtres.' },
  'admin.allSeasons': { en: 'All seasons', fr: 'Toutes les saisons' },
  'admin.noPlayerMatches': { en: 'No championship match for this player in this period.', fr: 'Aucun match de championnat pour ce joueur sur cette période.' },
  'admin.wonLost': { en: 'Won / Lost', fr: 'Gagné / Perdu' },
  'admin.winRate': { en: 'Win rate', fr: 'Taux de victoire' },
  'admin.winShort': { en: 'W', fr: 'G' },
  'admin.lossShort': { en: 'L', fr: 'P' },
  'admin.avgTrendTitle': { en: 'Average over time (per match)', fr: 'Moyenne dans le temps (par match)' },
  'admin.records': { en: 'Records', fr: 'Records' },
  'admin.headToHead': { en: 'Head-to-head', fr: 'Face-à-face' },
  'admin.bestMatchAvg': { en: 'Best match avg', fr: 'Meilleure moy. match' },
  'admin.most180Match': { en: 'Most 180s (match)', fr: 'Plus de 180 (match)' },
  'admin.selectOpponent': { en: 'Select an opponent…', fr: 'Choisir un adversaire…' },
  'admin.notEnoughTrend': { en: 'Not enough finished matches for a trend yet.', fr: 'Pas encore assez de matchs terminés pour une courbe.' },
  'admin.avgLegend': { en: '3-dart average per match', fr: 'Moyenne 3 fléchettes par match' },
  'admin.best': { en: 'Best {value}', fr: 'Meilleur {value}' },
  'admin.latest': { en: 'Latest {value}', fr: 'Dernier {value}' },
  'admin.recentMatches': { en: 'Recent matches', fr: 'Matchs récents' },
  'admin.trendAria': { en: '3-dart average trend by match', fr: 'Courbe de moyenne 3 fléchettes par match' },
  'admin.topAverages': { en: 'Top averages', fr: 'Meilleures moyennes' },
  'admin.most180s': { en: 'Most 180s', fr: 'Plus de 180' },
  'admin.mostLegsWon': { en: 'Most legs won', fr: 'Plus de legs gagnés' },
  'admin.seasonReviewTitle': { en: '🏆 Season review', fr: '🏆 Bilan de saison' },
  'admin.noSeasonMatches': { en: 'No championship match played in {season} yet.', fr: 'Aucun match de championnat joué sur {season} pour le moment.' },
  'award.mvp': { en: 'MVP (3-dart avg)', fr: 'MVP (moy. 3 fléchettes)' },
  'award.bestCheckout': { en: 'Best checkout', fr: 'Meilleur checkout' },
  'award.most180s': { en: 'Most 180s', fr: 'Plus de 180' },
  'award.bestFirst9': { en: 'Best First 9', fr: 'Meilleur First 9' },
  'award.mostLegsWon': { en: 'Most legs won', fr: 'Plus de legs gagnés' },
  'award.mostWins': { en: 'Most wins', fr: 'Plus de victoires' },
  'champ.loadingEncounter': { en: 'Loading team match…', fr: 'Chargement de la rencontre…' },
  'champ.matchOf': { en: 'Match {current} / {total}', fr: 'Match {current} / {total}' },
  'champ.left': { en: '{count} left', fr: '{count} restants' },
  'champ.configure': { en: '⚙ Configure', fr: '⚙ Configurer' },
  'champ.configureTitle': { en: 'Configure team match', fr: 'Configurer la rencontre' },
  'champ.legsToWin': { en: 'Legs to win', fr: 'Legs à gagner' },
  'champ.starts': { en: 'Throws first', fr: 'Lance en premier' },
  'champ.startMode': { en: 'Throw order', fr: 'Ordre de lancer' },
  'champ.bull': { en: 'Bull', fr: 'Bull' },
  'champ.fixed': { en: 'Fixed', fr: 'Fixe' },
  'champ.alternate': { en: 'Alternate', fr: 'Alterner' },
  'champ.notStartedApply': { en: 'Applies to matches not started yet.', fr: 'S’applique aux matchs pas encore démarrés.' },
  'champ.played': { en: 'played', fr: 'joué' },
  'champ.composeDoubles': { en: 'Compose the doubles', fr: 'Composer les doubles' },
  'champ.composeFirstSingles': { en: 'Compose the first singles', fr: 'Composer les premiers simples' },
  'champ.composeLastSingles': { en: 'Compose the last singles', fr: 'Composer les derniers simples' },
  'champ.double': { en: 'Double', fr: 'Double' },
  'champ.single': { en: 'Single', fr: 'Simple' },
  'champ.starting': { en: 'Starting…', fr: 'Démarrage…' },
  'champ.startEncounter': { en: 'Start team match ▶', fr: 'Démarrer la rencontre ▶' },
  'champ.continue': { en: 'Continue ▶', fr: 'Continuer ▶' },
  'champ.previousMatch': { en: '↩ Previous match', fr: '↩ Match précédent' },
  'champ.bullUp': { en: 'Bull-off', fr: 'Tirage au bull' },
  'champ.playersOrder': { en: 'Players (throwing order)', fr: 'Joueurs (ordre de lancer)' },
  'champ.players': { en: 'Players', fr: 'Joueurs' },
  'champ.whoWonBull': { en: 'Who won the bull-off and throws first?', fr: 'Qui a gagné le tirage au bull et lance en premier ?' },
  'champ.selectPlayersToStart': { en: 'Select {text} for each team to start.', fr: 'Sélectionnez {text} par équipe pour démarrer.' },
  'champ.twoPlayers': { en: 'two players', fr: 'deux joueurs' },
  'champ.onePlayer': { en: 'a player', fr: 'un joueur' },
  'champ.startMatch': { en: 'Start match ▶', fr: 'Démarrer le match ▶' },
  'champ.selectPlayer': { en: 'Select player', fr: 'Choisir un joueur' },
  'champ.loadingResult': { en: 'Loading result…', fr: 'Chargement du résultat…' },
  'champ.result': { en: 'result', fr: 'résultat' },
  'champ.seeFinal': { en: 'See final result ▶', fr: 'Voir le résultat final ▶' },
  'champ.continueToDecider': {
    en: 'Continue to decisive doubles ▶',
    fr: 'Continuer vers le double décisif ▶',
  },
  'champ.nextMatch': { en: '▶ Next match', fr: '▶ Match suivant' },
  'champ.finishEncounter': { en: 'Finish team match', fr: 'Terminer la rencontre' },
  'champ.matchFinishedSaving': { en: 'Match finished — saving…', fr: 'Match terminé — enregistrement…' },
  'champ.teamAvg': { en: 'team avg {value}', fr: 'moy. équipe {value}' },
  'champ.decider': { en: 'Decisive doubles', fr: 'Double décisif' },
  'champ.deciderTag': { en: '★ Decider', fr: '★ Décisif' },
  'champ.composeDecider': { en: 'Decisive doubles', fr: 'Double décisif' },
  'champ.deciderHint': {
    en: 'Level score — pick a fresh pair on each side (one that has not played together in this team match).',
    fr: 'Score à égalité — choisissez une paire inédite par équipe (qui n’a pas déjà joué ensemble dans cette rencontre).',
  },
  'champ.deciderPairUsed': {
    en: 'This pair has already played together — choose another.',
    fr: 'Cette paire a déjà joué ensemble — choisissez-en une autre.',
  },
  'champ.deciderSamePlayer': { en: 'Pick two different players.', fr: 'Choisissez deux joueurs différents.' },
  'champ.startDecider': { en: 'Start decisive doubles ▶', fr: 'Démarrer le double décisif ▶' },
  'champ.individualStats': { en: 'Individual statistics', fr: 'Statistiques individuelles' },
  'champ.noEncounters': { en: 'No championship team matches this season yet.', fr: 'Aucune rencontre de championnat pour cette saison.' },
  'editVisit.title': { en: 'Edit visit', fr: 'Modifier la volée' },
  'editVisit.specialTitle': { en: 'Special visit', fr: 'Volée spéciale' },
  'editVisit.help': { en: 'Visit score (0–180) — same rules as live entry. Everything recalculates instantly.', fr: 'Score de la volée (0–180) — mêmes règles que la saisie en direct. Tout est recalculé immédiatement.' },
  'editVisit.dartsUsed': { en: 'Darts used to check out', fr: 'Fléchettes utilisées pour finir' },
  'editVisit.notEditable': { en: 'This entry ({type}) cannot be edited.', fr: 'Cette entrée ({type}) ne peut pas être modifiée.' },
  'visitHistory.empty': { en: 'No visits yet this leg.', fr: 'Aucune volée pour ce leg.' },
  'encounterSetup.title': { en: 'Championship match', fr: 'Match de championnat' },
  'encounterSetup.description': { en: 'Team match — 4 singles, 2 doubles, 4 singles (10 matches), first to 2 legs.', fr: 'Rencontre par équipes — 4 simples, 2 doubles, 4 simples (10 matchs), premier à 2 legs.' },
  'encounterSetup.homeTeam': { en: 'Home team', fr: 'Équipe à domicile' },
  'encounterSetup.opponent': { en: 'Opponent', fr: 'Adversaire' },
  'encounterSetup.homeBadge': { en: 'Home', fr: 'Domicile' },
  'encounterSetup.pickBoth': { en: 'Pick both teams.', fr: 'Sélectionnez les deux équipes.' },
  'encounterSetup.differentTeams': { en: 'Teams must be different.', fr: 'Les équipes doivent être différentes.' },
  'encounterSetup.minPlayers': { en: 'Each team needs at least 4 players (add them under Statistics → Teams).', fr: 'Chaque équipe doit avoir au moins 4 joueurs (ajoutez-les dans Statistiques → Équipes).' },
  'encounterSetup.noSeason': { en: 'No current season.', fr: 'Aucune saison en cours.' },
  'encounterSetup.createFailed': { en: 'Failed to create team match', fr: 'Impossible de créer la rencontre' },
  'encounterSetup.noTeams': { en: 'No teams yet — create them under Statistics → Teams.', fr: 'Aucune équipe — créez-en dans Statistiques → Équipes.' },
  'encounterSetup.creating': { en: 'Creating…', fr: 'Création…' },
  'encounterSetup.composeFirst': { en: 'Compose first singles →', fr: 'Composer les premiers simples →' },
  'team.title': { en: 'My team', fr: 'Mon équipe' },
  'team.noTeamAssigned': {
    en: 'This account is not linked to a team yet. Ask the organizer to assign it.',
    fr: 'Ce compte n’est pas encore associé à une équipe. Demandez à l’organisateur de l’associer.',
  },
  'team.squad': { en: 'My squad', fr: 'Mon effectif' },
  'team.newEncounter': { en: 'New match', fr: 'Nouveau match' },
  'team.history': { en: 'History', fr: 'Historique' },
  'team.stats': { en: 'Stats', fr: 'Statistiques' },
  'team.mySquad': { en: 'Squad', fr: 'Effectif' },
  'team.noMembers': {
    en: 'No players in your squad yet — add some above.',
    fr: 'Aucun joueur dans votre effectif — ajoutez-en ci-dessus.',
  },
  'team.newPlayerName': { en: 'New player name', fr: 'Nom du nouveau joueur' },
  'team.createAndAdd': { en: '+ Create', fr: '+ Créer' },
  'team.addExisting': { en: 'Add a player', fr: 'Ajouter un joueur' },
  'team.remove': { en: 'Remove', fr: 'Retirer' },
  'team.removeMemberTitle': { en: 'Remove {name} from the squad?', fr: 'Retirer {name} de l’effectif ?' },
  'team.removeMemberMessage': {
    en: 'The player stays in the club and keeps their history — they are only removed from your squad.',
    fr: 'Le joueur reste dans le club et conserve son historique — il est seulement retiré de votre effectif.',
  },
  'team.pickOpponent': { en: 'Pick an opponent.', fr: 'Choisissez un adversaire.' },
  'team.needFourOwn': {
    en: 'Your squad needs at least 4 players (add them under My squad).',
    fr: 'Votre effectif doit compter au moins 4 joueurs (ajoutez-les dans Mon effectif).',
  },
  'team.noOpponents': {
    en: 'No other team to play against yet.',
    fr: 'Aucune autre équipe disponible pour le moment.',
  },
  'team.noEncounters': {
    en: 'No championship match played yet.',
    fr: 'Aucun match de championnat joué pour le moment.',
  },
};

interface LangValue {
  lang: Lang;
  setLang: (l: Lang) => void;
  t: (key: string) => string;
}
const LangContext = createContext<LangValue | null>(null);

export function LangProvider({ children }: { children: ReactNode }) {
  const [lang, setLangState] = useState<Lang>(() => {
    try {
      const s = localStorage.getItem(KEY);
      if (s === 'fr' || s === 'en') return s;
    } catch {
      /* ignore */
    }
    return typeof navigator !== 'undefined' &&
      navigator.language?.toLowerCase().startsWith('fr')
      ? 'fr'
      : 'en';
  });
  const setLang = useCallback((l: Lang) => {
    setLangState(l);
    try {
      localStorage.setItem(KEY, l);
    } catch {
      /* ignore */
    }
  }, []);
  const t = useCallback((key: string) => DICT[key]?.[lang] ?? key, [lang]);
  const value = useMemo(() => ({ lang, setLang, t }), [lang, setLang, t]);
  return <LangContext.Provider value={value}>{children}</LangContext.Provider>;
}

export function useT(): LangValue {
  const ctx = useContext(LangContext);
  if (!ctx) throw new Error('useT must be used within a LangProvider');
  return ctx;
}

/** FR / EN switch. */
export function LangToggle() {
  const { lang, setLang } = useT();
  return (
    <div className="inline-flex overflow-hidden rounded-lg border border-[var(--color-border)] text-xs">
      {(['fr', 'en'] as const).map((l) => (
        <button
          key={l}
          onClick={() => setLang(l)}
          className={cn(
            'px-2.5 py-1 font-bold uppercase transition-colors',
            lang === l
              ? 'bg-[var(--color-accent)] text-white'
              : 'text-[var(--color-text-dim)] hover:text-[var(--color-text)]',
          )}
        >
          {l}
        </button>
      ))}
    </div>
  );
}
